global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'sre-microservice'
    static_configs:
      - targets: ['sre-microservice:80']
    metrics_path: '/metrics'
